version: "3"

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./data/:/usr/src/app/data/
    env_file:
      - .env
    command: python main.py
  
  cron:
    container_name: cron
    build: .
    volumes:
      - ./data/:/usr/src/app/data/
    env_file:
      - .env
    command: python main.py

