version: "3"

services:
  cron:
    container_name: cron
    build: .
    volumes:
      - ./data/:/usr/src/app/data/
    env_file:
      - .env
    command: python github.py

  reddit:
    container_name: reddit
    build: .
    volumes:
      - ./data/:/usr/src/app/data/
    env_file:
      - .env
    command: python reddit.py
