# Generated by Django 4.2.6 on 2023-10-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh_id', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('watchers', models.IntegerField()),
                ('open_issues_count', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('udpated_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('topics', models.TextField()),
                ('avatar_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='sources.githubuser')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='sources.repository')),
            ],
        ),
    ]
