# Generated by Django 4.2.6 on 2023-10-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_remove_repository_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
