# Generated by Django 4.2.6 on 2023-10-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_rename_udpated_at_repository_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='hash',
            new_name='sha',
        ),
    ]
