# Generated by Django 4.2.6 on 2023-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_alter_commit_developer_alter_repository_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
