[theme]
base="dark"
primaryColor="#E694FF"
backgroundColor="#00172B"
secondaryBackgroundColor="#0083B8"
textColor="#DCDCDC"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
